extensions/openpower-pels/registry/message_registry.json
Added error log entry for memory preserving reboot might failure. 
https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/54427
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Change-Id: Iceaf21c6527ccf93bcb11b8ec1c9c55dc3670ae0
=> PEL: Add error log entry for memory preserving reboot failure

extensions/openpower-pels/registry/message_registry.json
Add entries for errors that occur which are specific to
phosphor-bmc-code-mgmt. After code updates, and the system is
rebooted, there are partitions that should be preserved and not
overwritten. There needs to be PEL that specify if any of the
partitions have been corrupted or modified in a way that
prevents the copy from happening.
=> PEL: phosphor-bmc-code-mgmt add HostFile

extensions/openpower-pels/registry/message_registry.json
The commit defines interface for essential fru missing case.
Essential frus are the ones which are required to be present
in the system at power on state.
The commit also modifies the entry related GPIO line error,
where because of the ambiguity behind GPIO line error, bmc
code will be called out.
Signed-off-by: Sunny Srivastava <sunnsr25@in.ibm.com>
Change-Id: I167c45ed384e04676d66887bcecb4e7e00f16709
=> PEL: Error interface for missing essential fru. SW553167

extensions/openpower-pels/manager.cpp, extensions/openpower-pels/manager.hpp, test/openpower-pels/pel_manager_test.cpp
The Resolution D-Bus property is filled with values from the PEL callout
fields like the serial and part numbers.  These fields usually come from
EEPROMs, and may not necessarily be valid printable values if the code
that creates the PEL doesn't sanitize the values first.  If any of the
characters were invalid, the daemon would crash when D-Bus broker
disconnects it from D-Bus since it doesn't allow invalid values on
D-Bus.
Prevent this crash by converting any non printable characters in the
Resolution property to spaces.  This also sanitizes the EventId property
which contains the SRC ASCII string and hex words just to be safe.
This is really just a concern for non-BMC created PELs, since the BMC
code that reads EEPROMs already sanitizes the values when it reads them,
but PELs have come …
=> PEL: Sanitize D-Bus fields that come from PELs

extensions/openpower-pels/registry/message_registry.json
- Enables the documented SRC for PLDM PELs in peltool.
Tested with validator - openpower-pels/registry/tools/process_registry.py
Change-Id: I2cd1cd2cbb4535996d77e05caf52cd371fa6fad1
Signed-off-by: Sridevi Ramesh <sridevra@in.ibm.com>
=> Add support for PLDM error logging in message_registry.json.

extensions/openpower-pels/pel_values.cpp, extensions/openpower-pels/registry.cpp, extensions/openpower-pels/registry/README.md, extensions/openpower-pels/registry/message_registry.json, extensions/openpower-pels/registry/schema/schema.json, test/openpower-pels/registry_test.cpp
These commits add the OVERTMP symbolic FRU as a high callout to the perfloss, warning, and critical high temperature PELs.  It uses a new CalloutsWhenNoADMatch message registry field to handle doing it for all sensors listed in the ADValue field that aren't the ambient sensor.
=> Overtemp callouts

extensions/openpower-pels/registry/message_registry.json
Added message registry for logging guard partition access error At the time of IPLing if we are unable to access guard partition, this entry is logged as informational and the required fields are enabled to reports externally.
Signed-off-by: deepakala karthikeyan <deepakala.karthikeyan@ibm.com>
Change-Id: I7874f81932c12043f5f8641058fcf59e60d63410
=> PEL: Add registry for logging Guard partition access error

gen/meson.build, gen/xyz/openbmc_project/Logging/Internal/Manager/meson.build, gen/xyz/openbmc_project/Logging/Internal/meson.build, meson.build, tools/meson.build, tools/phosphor-logging/templates/meson.build
These were actually getting installed into the BMC flash image, which isn't desirable.  Bitbake runs these straight from the source tree so removing this doesn't affect builds.
This does mean they wouldn't be installed into usr/share in the SDK, but it's not like that was in $PATH anyway.
https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/57999
Change-Id: I65fff38bcdf82e8b812177d65a6918fc9abbd5fd
=> Don't install elog-gen.py and mako templates

extensions/openpower-pels/registry/message_registry.json
The UnTarFailure can be caused by uploading accidentally the wrong image format, and therefore does not require to be a call-home error since the user can figure that error themselves, or if they need to, they can call home themselves.
Set the Action Flags to report to override the default that adds the call home flag, instead of changing the severity to non_error, in this way the error severity is preserved and it's viewable by all users.
Tested: Error log diff:
<     "Action Flags": [
<                                 "Service Action Required",
<                                 "Report Externally",
<                                 "HMC Call Home"
---
>     "Action Flags": [
>                                 "Report Externally"
The error log is present in the GUI.
Change-Id: …
=> PEL: Set Action Flags for UnTarFailure to report only

elog_entry.cpp, extensions/openpower-pels/repository.cpp
There were two cases where a fopen was followed by an fclose.  Change the code to just use an open() instead of fopen() as a close() was already being called.
Defect: PE00F7PV
Upstream: https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/60256
=> Fix memory leaks in PEL daemon

extensions/openpower-pels/data_interface.cpp, extensions/openpower-pels/data_interface.hpp, extensions/openpower-pels/service_indicators.cpp, extensions/openpower-pels/src.cpp, test/openpower-pels/mocks.hpp, test/openpower-pels/pel_manager_test.cpp, test/openpower-pels/pel_test.cpp, test/openpower-pels/service_indicators_test.cpp, test/openpower-pels/src_test.cpp
DataInterface::getInventoryFromLocCode() was only returning a single inventory path from GetFRUsByExpandedLocationCode() even though multiple paths may have been returned.
Mostly that was fine, except when a processor on a DCM was called out. That would lead to only one processor on the DCM being set to not functional by service_indicators.cpp, so on the web UI the actual CPU called out may not have been marked as unhealthy (health status critical in Redfish).
This commit changes getInventoryFromLocCode() to return all the paths that GetFRUsByExpandedLocationCode() returns, and then makes the corresponding changes in service_indicators.cpp to be able to handle multiple inventory paths per location code when setting them to not functional and creating a critical association.
The other code …
=> PEL: Handle multiple inv paths per loc code

extensions/openpower-pels/registry/message_registry.json
```
Adding a PEL entry into message_registry.json file for dump delete.
Default severity is informational and can be overwritten by caller
Change-Id: I71520889bc9c7b0f2f3d401eb513292aeb2f8994
Change-Id: I6d5af1d5a1720ef856642aabae768a30fa36db7d
Signed-off-by: Swarnendu Roy Chowdhury <swarnendu.roy.chowdhury@ibm.com>
```
=> 1030: PEL: Adding a PEL message entry into message_registry.json file

dist/dbus/xyz.openbmc_project.Logging.service, dist/meson.build, dist/xyz.openbmc_project.Logging.service
Add support for dbus activation of phosphor-logging. This will ensure users of the logging library for calls like "commit" will automatically have the phosphor-logging service start (if not already running) and not need to put this dependency in their service files.
Tested:
- Stopped xyz.openbmc_project.Logging.service and then used busctl to create an error log. Verified that xyz.openbmc_project.Logging.service was automatically started and the error was created.
Change-Id: I9134851c075dbb717f832422f55e2eeee31f823b
=> dbus: add dbus activation support

extensions/openpower-pels/registry.cpp, extensions/openpower-pels/registry.hpp, extensions/openpower-pels/registry/README.md, extensions/openpower-pels/registry/message_registry.json, extensions/openpower-pels/registry/schema/schema.json, extensions/openpower-pels/src.cpp, extensions/openpower-pels/src.hpp, test/openpower-pels/registry_test.cpp, test/openpower-pels/src_test.cpp
```
Similiar to the DeconfigFlag field that was recently added, this one
indicates the PEL is for a hardware checkstop and results in a bit in
SRC hex word 5 being set.
Change-Id: Ib05de7471ad3e32f48e7f20a5c611abc119fe82a
```
=> 1020: PEL: Support for CheckstopFlag msg reg field

extensions/openpower-pels/sbe_ffdc_handler.cpp, extensions/openpower-pels/sbe_ffdc_handler.hpp
The descriptors were being leaked since deleting the file doesn't close the FD which was explicitly opened earlier.
Change-Id: I5d0f1ed91f38af6830ea4f3c600adc402102564c
=> PEL: Close SBE FFDC file descriptors

extensions/openpower-pels/sbe_ffdc_handler.cpp, extensions/openpower-pels/sbe_ffdc_handler.hpp
```
The descriptors were being leaked since deleting the file doesn't close
the FD which was explicitly opened earlier.
Change-Id: I5d0f1ed91f38af6830ea4f3c600adc402102564c
```
=> 1020: PEL: Close SBE FFDC file descriptors

extensions/openpower-pels/host_notifier.cpp
The PLDM daemon was missing the call to HostReject when PHYP responded to getting a new PEL with the 'file discarded' response.  Now that it's being added, this trace was showing up multiple times as PHYP would accept one new PEL at a time as the OS slowly acked them.
Change-Id: I13bccf821b96a8d918d33646893efa34faf4c088
=> PEL: Change info trace to a debug one

extensions/openpower-pels/sbe_ffdc_handler.cpp, extensions/openpower-pels/sbe_ffdc_handler.hpp
```
The descriptors were being leaked since deleting the file doesn't close
the FD which was explicitly opened earlier.
Change-Id: I5d0f1ed91f38af6830ea4f3c600adc402102564c
```
=> 1030: PEL: Close SBE FFDC file descriptors

extensions/openpower-pels/registry/message_registry.json
```
During chassis poweron current system time is written to a persistent
file that is used to ignore old power or thermal errors as part of
faultlog dump/pel generation.
Add error log entries for failure to read/write from the persistent
file.
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Change-Id: I70420b529d930fee833402d1b3276ffb1ec2a518
```
=> 1050: PEL: Add error log entries for faultlog poweron time read/write

extensions/openpower-pels/registry/message_registry.json
```
During chassis poweron current system time is written to a persistent
file that is used to ignore old power or thermal errors as part of
faultlog dump/pel generation.
Add error log entries for failure to read/write from the persistent
file.
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Change-Id: I70420b529d930fee833402d1b3276ffb1ec2a518
```
=> 1060: PEL: Add error log entries for faultlog poweron time read/write

extensions/openpower-pels/bcd_time.cpp, extensions/openpower-pels/data_interface.cpp, extensions/openpower-pels/entry_points.cpp, extensions/openpower-pels/extended_user_data.cpp, extensions/openpower-pels/extended_user_header.cpp, extensions/openpower-pels/failing_mtms.cpp, extensions/openpower-pels/fapi_data_process.cpp, extensions/openpower-pels/fru_identity.cpp, extensions/openpower-pels/generic.cpp, extensions/openpower-pels/journal.cpp, extensions/openpower-pels/manager.cpp, extensions/openpower-pels/pel.cpp, extensions/openpower-pels/phal_service_actions.cpp, extensions/openpower-pels/private_header.cpp, extensions/openpower-pels/sbe_ffdc_handler.cpp, extensions/openpower-pels/service_indicators.cpp, extensions/openpower-pels/src.cpp, extensions/openpower-pels/user_data.cpp, extensions/openpower-pels/user_header.cpp
fmt::format is supported in the c++ std. This will
help to remove fmt package dependency.
Change-Id: I89f0a5b67bbfe54168a20e93c989a1ae87f54503
=> PEL: switch fmt::format to use std::format

extensions/openpower-pels/json_utils.hpp
A static analysis security scanner (HCL AppScan SAST) flagged the asprintf call as a vulnerability because the format string is passed in.
While really it isn't an issue because the format string is always hardcoded in the calling function and isn't input by a user, this commit changes it anyway to get it off the list.
Use snprintf instead.  While it still takes a passed in format string, a hardcoded maximum length is used so that the scanner shouldn't flag it as a possible buffer overrun.
Change-Id: Ife309b63470536940ac88c27d13fe73716096326
=> PEL: Change asprintf call to snprintf

extensions/openpower-pels/meson.build, extensions/openpower-pels/registry/message_registry.json, gen/xyz/openbmc_project/Logging/meson.build, gen/xyz/openbmc_project/meson.build, log_manager.hpp, subprojects/nlohmann-json.wrap, subprojects/nlohmann_json.wrap, test/meson.build, yaml/xyz/openbmc_project/Logging.errors.yaml, yaml/xyz/openbmc_project/Logging.metadata.yaml
The community added code to create an informational event log when all event logs are deleted.  This is what we did on FSP, so pulling it in here too.
Also pulling in the commits to fixup the OCC error names so they match what is being created.
https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/68609
=> Fixup OCC error names and add LogsCleared informational PEL

extensions/openpower-pels/registry/README.md, extensions/openpower-pels/registry/message_registry.json, extensions/openpower-pels/registry/schema/registry_example.json, extensions/openpower-pels/registry/schema/schema.json, extensions/openpower-pels/src.cpp, test/openpower-pels/pel_manager_test.cpp, test/openpower-pels/registry_test.cpp, test/openpower-pels/src_test.cpp
Use the actual names so that the script that creates IBM's documentation (RCDL files) can pull them in, so that they will show up with the SRCs on IBM's web site.
The other commit is to add some missing SRCs.
=> Use raw procedure names in PEL message registry.

extensions/openpower-pels/registry/README.md, extensions/openpower-pels/registry/message_registry.json, extensions/openpower-pels/registry/schema/registry_example.json, extensions/openpower-pels/registry/schema/schema.json, extensions/openpower-pels/src.cpp, test/openpower-pels/pel_manager_test.cpp, test/openpower-pels/registry_test.cpp, test/openpower-pels/src_test.cpp
Use the actual names so that the script that creates IBM's documentation (RCDL files) can pull them in, so that they will show up with the SRCs on IBM's web site.
The other commit is to add some missing SRCs.
=> Use raw procedure names in PEL message registry

extensions/openpower-pels/registry/message_registry.json
The Temperature/Voltage CriticalHigh/Low PELs previously had a PEL severity of 'predictive', and this commit changes them to 'unrecoverable' so that it matches the D-Bus severity value it's being created with.
Note: The D-Bus severity value is 'critical'.  While there is a PEL severity value of 'critical', both 'unrecoverable' and 'critical' get mapped to the Redfish field value of 'Critical' anyway, and the PEL 'critical' field seems to be just used for system crashes and the like.
Change-Id: I174c48180abe9ddca09d0e020e6d16f81311bb61
=> PEL: Update sev of critical threshold errors

dist/busconfig/phosphor-auditlog-config.conf, dist/meson.build, dist/xyz.openbmc_project.Logging.AuditLog.service, meson.build, phosphor-auditlog/alog_manager.cpp, phosphor-auditlog/alog_manager.hpp, phosphor-auditlog/alog_parser.cpp, phosphor-auditlog/alog_parser.hpp, phosphor-auditlog/alog_utils.hpp, phosphor-auditlog/main.cpp, phosphor-auditlog/meson.build
Scaled down implementation of upstream design still under review [1].
This implements scaled down downstream PDI interface [2].
```
$ busctl tree xyz.openbmc_project.Logging.AuditLog
`- /xyz
`- /xyz/openbmc_project
`- /xyz/openbmc_project/logging
`- /xyz/openbmc_project/logging/auditlog
$ busctl introspect xyz.openbmc_project.Logging.AuditLog /xyz/openbmc_project/logging/auditlog
NAME                                 TYPE      SIGNATURE  RESULT/VALUE  FLAGS
org.freedesktop.DBus.Introspectable  interface -          -             -
.Introspect                          method    -          s             -
org.freedesktop.DBus.ObjectManager   interface -          -             -
.GetManagedObjects                   method    -          a{oa{sa{sv}}} -
.InterfacesAdded …
```
=> Audit Log: Implement phosphor-auditlog D-Bus interface

phosphor-auditlog/alog_parser.cpp
Include only the AUDIT_USYS_CONFIG audit records for getLatestEntries. This method provides support for the GUI to display audit records. The GUI display is limited to audit records with known fields provided by the AUDIT_USYS_CONFIG records.
=> Audit Log: Return only AUDIT_USYS_CONFIG  records for getLatestEntries

docs/structured-logging.md, extensions/openpower-pels/callout.cpp, extensions/openpower-pels/callout.hpp, extensions/openpower-pels/callouts.cpp, lib/include/phosphor-logging/lg2/conversion.hpp, test/openpower-pels/pel_test.cpp, test/openpower-pels/src_callout_test.cpp, test/openpower-pels/src_callouts_test.cpp
When adding callouts, check if the callout being added already exists.
If it does, don't add it and rather just update the priority of the
existing one to be the highest of the two.
Callouts are considered to be equal if their location code matches, or
if they have the same maintenance procedure, or if they have the same
symbolic FRU
This also pulls in some upstream changes to allow lg2 handling of printing enums natively.
Everything here is already merged upstream.
https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/69682
=> Don't allow duplicate PEL callouts

phosphor-auditlog/alog_parser.cpp, phosphor-auditlog/alog_parser.hpp
A malformed audit log record being parsed can cause confusion. Don't include these records for the getLatestEntries() method. Add warning message to the journal for any of these records seen to facilitate future debugging.
Fixes: 600216
Tested: Recreated bmcweb core dump. Installed fix and tried again. Confirmed malformed entries are not returned and journal message for debugging is recorded.
Fix for bmcweb also coded: https://github.com/ibm-openbmc/bmcweb/pull/842
=> Audit Log: RAS: Skip records which duplicate fields

extensions/openpower-pels/registry/O_component_ids.json, extensions/openpower-pels/registry/message_registry.json
Parser to parse the POZ PLAT data in the PEL. Changing the component ID from F400 to 4500 to be used for all the SBE's PEL data parsers. "o3500.py" will handle only P10 processor SBE. "o4500.py" will be for Odyssey and Pfuture chips.
Change-Id: I4be341888b6ea7a0b999b3e4555604b4d39ea4ce
=> PEL: Add POZ PEL Parser

extensions/openpower-pels/registry/message_registry.json
```
Tested:
Injected a error and verified the output
busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
xyz.openbmc_project.Logging.Create Create ssa{ss} \
xyz.openbmc_project.State.Shutdown.Power.Error.Regulator \
xyz.openbmc_project.Logging.Entry.Level.Critical 0
'''
peltool -l
{
"0x5000012C": {
"SRC":                  "11002602",
"Message":              "A power off was issued because a regulator for standby power faulted",
"PLID":                 "0x5000012C",
"CreatorID":            "BMC",
"Subsystem":            "Power Control Hardware",
"Commit Time":          "03/28/2024 02:49:10",
"Sev":                  "Critical Error, System Termination",
"CompID":               "bmc power and thermal"
}
}
'''
peltool -i 0x5000012C
{
"Private Header": {
"Section Version": …
```
=> 1060: PEL: Fix PEL to callout PGDPART symbolic FRU

dist/busconfig/phosphor-auditlog-config.conf, dist/meson.build, dist/xyz.openbmc_project.Logging.AuditLog.service, meson.build, meson.options, phosphor-auditlog/alog_manager.cpp, phosphor-auditlog/alog_manager.hpp, phosphor-auditlog/alog_parser.cpp, phosphor-auditlog/alog_parser.hpp, phosphor-auditlog/alog_utils.hpp, phosphor-auditlog/main.cpp, phosphor-auditlog/meson.build
This PR rebases all Audit Log PRs from 1060. Additionally a new commit is added to build phosphor-auditlog under compile time control. A separate openbmc/openbmc PR will be merged to enable this option.
PRs rebased:
- https://github.com/ibm-openbmc/phosphor-logging/pull/41
- https://github.com/ibm-openbmc/phosphor-logging/pull/49
- https://github.com/ibm-openbmc/phosphor-logging/pull/51
=> 1110 Audit Log Rebase

extensions/openpower-pels/registry/message_registry.json
```
In the newly introduced PEL in the callout details
we had procedure name as "next_level_support" but
recently made a change to expose the procedure
callouts in the RCDL because service said they needed
them. This changes fixes this missing actual procedure
name from next_level_support to BMC0002.
Signed-off-by: Swarnendu Roy Chowdhury <swarnendu.roy.chowdhury@ibm.com>
Change-Id: I7f49ca37cef3c6f49fc08808b68fdd9f72549b25
```
=> 1060: PEL: Fixing procedure name in callout details

extensions/openpower-pels/registry/message_registry.json
```
This commit updates the severity of  PEL
'xyz.openbmc_project.PLDM.Error.SetHostEffecterFailed' from
UNRECOVERABLE ERROR to INFORMATIONAL.
Signed-off-by: Riya Dixit <riyadixitagra@gmail.com>```
=> 1050: PEL: Updating sev for set host effecter failure (#60)

extensions/openpower-pels/registry/message_registry.json
```
This commit updates the severity of  PEL
'xyz.openbmc_project.PLDM.Error.SetHostEffecterFailed' from
UNRECOVERABLE ERROR to INFORMATIONAL.
Signed-off-by: Riya Dixit <riyadixitagra@gmail.com>
```
=> 1030: PEL: Updating sev for set host effecter failure (#60)

extensions/openpower-pels/registry/message_registry.json
This commit adds BMC pels for PLDM error so as to report resource dump failure.
=> PEL: Adding BMC PEL for PLDM error

extensions/openpower-pels/data_interface.cpp, extensions/openpower-pels/data_interface.hpp, extensions/openpower-pels/entry_points.cpp, extensions/openpower-pels/meson.build, extensions/openpower-pels/pel.cpp, extensions/openpower-pels/pel.hpp, extensions/openpower-pels/phal_service_actions.cpp, extensions/openpower-pels/registry/README.md, extensions/openpower-pels/sbe_ffdc_handler.cpp, test/openpower-pels/meson.build, test/openpower-pels/mocks.hpp, test/openpower-pels/pel_test.cpp
Add the called out DIMMs DRAM manufacturer info to the user data section of the PEL to assist the service engineers in identifying the manufacturer of the faulty DRAMs packaged within the DIMM module directly from the logs, aiding in quick resolution.
The changes also moves the pdbg target and libekb initialization to the PEL startup which avoids the need of multiple initialization as the existing design.
When a PEL calls out a DIMM FRU, the DRAM manufacturer ID and the expanded location code of those DIMMs are added to the SysInfo user data section  of the generated PEL in JSON format under the key 'DIMMs Additional Info'.
In case of  any errors occur during the collection or processing of the manufacturer data, the error messages will be logged in the 'PEL Internal Debug Data' section …
=> PEL: Add the DRAM manufacturer info of DIMM callout in UD section

extensions/openpower-pels/data_interface.cpp
It is observed in journal traces that that the phosphor-log-manager is receiving error trace as 'Failed to unsubscribe from JobRemoved systemd signal' during host factory reset
Root cause:
- It is observed that the systemd service `openpower-update-bios-attr-table.service` is starting again during host factory reset which is responsible for the PNOR symlink creation and update.
- In the existing code `JobRemoved` signal is subscribed for `openpower-update-bios-attr-table.service`
- In systemd signal , if at least one client is subscribed for a signal, most of the signals will sent out to the clients even if the current client unsubscribed.
- Since many other service including phosphor-state-manager is also subscribed for the signal and is not unsubscribed. Hence Phosphor-logging is …
=> PEL: DRAM Fix: Reset JobRemoved signal watcher

extensions/openpower-pels/data_interface.cpp, extensions/openpower-pels/data_interface.hpp, extensions/openpower-pels/meson.build, extensions/openpower-pels/pel.cpp, extensions/openpower-pels/phal_service_actions.cpp, extensions/openpower-pels/phal_service_actions.hpp, phosphor-auditlog/alog_manager.hpp, phosphor-auditlog/alog_parser.cpp, phosphor-auditlog/alog_utils.hpp
Replace CreateWithEntityPath D-Bus method with guard library calls for creating guard entries, as CreateWithEntityPath is not an approved dbus method.
Tested and the guard record is created with the corresponding PEL id
```
before injecting the error
root@p10bmc:~# guard -l
No unresolved records to display
After injecting error, the guard is created using the PEL ID
root@p10bmc:~# guard -l
ID         | ERROR      | Type            | Path
0x00000001 | 0x5000592b | unrecoverable   | physical:sys-0/node-0/proc-0/eq-1/fc-0/core-0
root@p10bmc:~# peltool -l
{
"0x5000592B": {
"SRC":                  "BD13E510",
"Message":              "Error Signature: 0x20DA0020 0x00000001 0x4D740407",
"PLID":                 "0x5000592B",
"CreatorID":            "BMC",
"Subsystem":            "Processor Unit …
```
=> openpower-pels: Create guard using libguard

extensions/openpower-pels/data_interface.cpp
The initialization of libguard was being skipped because the device tree was not set up during the initial phosphor-logging phase. As a result, all guard library calls failed, preventing the creation of system guards in the event of an error.
To address this, the libguard initialization has been moved to the point where guard creation occurs. Since libguard initialization is lightweight, this change has no noticeable impact on performance.
The fix has been tested, and guards are now correctly created as expected.
```
root@p10bmc:~# putscom pu.c 20018600 8000000000000000 -n0 -p0 -cft
pu.c    k0:n0:s0:p00:c0
/usr/bin/edbg putscom pu.c 20018600 8000000000000000 -n0 -p0 -cft
root@p10bmc:~# guard -l
ID         | ERROR      | Type            | Path
0x00000001 | 0x50000a78 | unrecoverable   | …
```
=> openpower-pels: Fix libguard initialization

extensions/openpower-pels/registry/message_registry.json
Add the procedure BMC0005 as a high priority callout for pgood errors on the 3V3IO voltage rail.  Reduce first VRM callout to medium priority.
When the lid (cover) is removed on Everest/Fuji systems, main power is automatically shut off for safety reasons.  Due to the hardware design and UCD configuration, the resulting pgood error is incorrectly isolated to the 3V3IO voltage rail.  Add the BMC0005 procedure as the first callout for this error so the lid will be checked as a possible cause.
Tested:
* Created 11002620 error for the 3V3IO rail using busctl.
* Verified all callouts in the resulting error log were correct.
Change-Id: I3af8ce6ae146ff8c6816602a2bfa47e679268387
=> openpower-pels: Add BMC0005 callout to pgood error

extensions/openpower-pels/registry/README.md
Something new in the docker container is forcing 80 char line wraps
=> 1110: fix up CI formatting

extensions/openpower-pels/registry/message_registry.json
We log the same error for Dump Delete and Offload right now. Adding a new error to distinguish between a dump delete and a dump offload.
Change-Id: I19282b3e7971702b6b3756aaf060ceeb200d2f94
=> Add a new error message for Dump Offload

extensions/openpower-pels/pldm_interface.cpp, extensions/openpower-pels/pldm_interface.hpp, log_manager.cpp
This call to ensure the PLDM response matches the PLDM request for the 'New PEL Available' command was previously missing (since it didn't exist at the time this code was written), causing the code to think it got the correct response when really it was someone else's.
It would then move on to the next PEL before it actually heard back about the current one, causing issues on the host side.
Change-Id: I471d7727a2b8c77a0ffc85c15cef7531898d22d7
=> PELs: Use pldm_msg_hdr_correlate_response()

extensions/openpower-pels/registry/message_registry.json
We log the same error for Dump Delete and Offload right now. Adding a new error to distinguish between a dump delete and a dump offload.
Change-Id: I1c74906fb170d883447a021c59199baaa4f6dc97
=> PEL: Add a new error message for Dump Offload

extensions/openpower-pels/manager.cpp
- This ensures that PEL objects are deleted if PEL files are deleted, irrespective of links to HWIsolation records.
Tested:
Sample output:
```bash
$ busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/
logging/entry/3 xyz.openbmc_project.Object.Delete Delete
Call failed: The service is temporarily unavailable.
$ peltool -D
```
PEL entry 3 was deleted in above example.
Change-Id: I416fad1d9dc832393b1ba689d582c602e27c79c6
Signed-off-by: Harsh Agarwal <Harsh.Agarwal@ibm.com>
Upstream [Patch](https://gerrit.openbmc.org/c/openbmc/phosphor-logging/+/79021).
=> PEL: Enable deletion if PEL file is deleted

extensions/openpower-pels/manager.cpp
```
- This ensures that PEL objects are deleted if PEL files are
deleted, irrespective of links to HWIsolation records.
Tested:
Sample output:
```bash
$ busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/
logging/entry/3 xyz.openbmc_project.Object.Delete Delete
Call failed: The service is temporarily unavailable.
$ peltool -D
```
PEL entry 3 was deleted in above example.
Change-Id: I416fad1d9dc832393b1ba689d582c602e27c79c6
Signed-off-by: Harsh Agarwal <Harsh.Agarwal@ibm.com>```
=> 1120: PEL: Enable deletion if PEL file is deleted (#92)

extensions/openpower-pels/src.cpp, extensions/openpower-pels/src.hpp, test/openpower-pels/pel_manager_test.cpp, test/openpower-pels/src_test.cpp
If the call to expand a location code in a PEL callout fails, still add the unexpanded version as a callout and also don't fill in the VPD sections in the callout.
This also picks up a testcase commit to remove  a temporary file when done.
=> Still create callouts even with just unexpanded location codes

elog_serialize.cpp
If an exception were to escape during an event log restore, phosphor-log-manager would just keep continuously crashing and restarting.
To prevent this, just catch all exceptions and move the file that caused it to /var/lib/phosphor-logging/corrupt_error so that it is kept around for debug if desired.  Only the most recent bad file is kept.
Tested:
Instead of crashing, the daemon can now stay up:
```
Mar 19 14:10:06 p10bmc phosphor-log-manager[2953]: Failed restoring /var/lib/phosphor-logging/errors/381: std::bad_alloc
/var/lib/phosphor-logging# ls -l /var/lib/phosphor-logging/corrupt_error
-rw-r--r--    1 root     root           374 Mar 19 13:39 /var/lib/phosphor-logging/corrupt_error
```
Change-Id: Iaa30dff261bbbe048cbca5678f2940cb2a8ed1df
=> Catch all exceptions when de-serializing

.secrets.baseline
This creates a baseline file (and initial responses to any potential secrets found).
After this file is merged, all CI jobs after will run the detect-secrets tool against incoming commits to verify no potential secrets are being shared. If one is found, CI will fail until the .secrets.baseline is updated for the new issue.
See the following for more info:
https://github.com/IBM/detect-secrets
=> 1120: CI-only: create detect-secrets baseline file

extensions/openpower-pels/registry/message_registry.json
The commit adds new error to call out procedure in case there is any std::runtime exception in the VPD Manager.
=> Add firmware error for VPD

extensions/openpower-pels/registry/message_registry.json
```
The commit adds new error to call out procedure in case there is any std::runtime exception in the VPD Manager.```
=> 1120: Add firmware error for VPD (#102)

extensions/openpower-pels/data_interface.cpp, extensions/openpower-pels/data_interface.hpp, extensions/openpower-pels/dbus_types.hpp, extensions/openpower-pels/manager.cpp, test/openpower-pels/mocks.hpp
The first entry in the std::tuple of the Value property, which is used to hold the 8 character SRC refcode, changed from a uint64_t to a std::vector<uint8_t>.  Make the necessary updates.
Tested:
Create a PEL with a severity value of 0x51 = critical system termination.  It has the refcode sent to this Value property:
```
$ busctl get-property xyz.openbmc_project.State.Boot.Raw \
/xyz/openbmc_project/state/boot/raw0 \
xyz.openbmc_project.State.Boot.Raw Value
(ayay)
8 49 49 48 48 50 54 48 50
^^ this is the correct 8 byte 11002602 refcode
and the rest is the 72 byte progress SRC:
72 2 9 0 9 0 0 0 188 0 0 0 85 46 45 0
16 0 0 0 0 32 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 49 49 48 48 50 54 48
50 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32 32
```
And now create another …
=> PEL: Fixes for State.Boot.Raw Value updates

extensions/openpower-pels/src.cpp, extensions/openpower-pels/user_data_json.cpp
```
Explicitly check if the UserData or SRC python plugin parsers return a
python None object and just return immediately.  In the UserData case
this results in a hex dump, and in the SRC case it just won't print the
SRC description.
Otherwise, peltool will crash when it tries to extract a string from the
result.
Tested:
peltool no longer crashes.
Change-Id: I2cb87a6071ecc2cbeb9df055f13039ad31fc6384
Signed-off-by: Matt Spinler <spinler@us.ibm.com>```
=> 1120: PEL: Check for Py_None from parser calls (#108)

extensions/openpower-pels/src.cpp, extensions/openpower-pels/user_data_json.cpp
```
Explicitly check if the UserData or SRC python plugin parsers return a
python None object and just return immediately.  In the UserData case
this results in a hex dump, and in the SRC case it just won't print the
SRC description.
Otherwise, peltool will crash when it tries to extract a string from the
result.
Tested:
peltool no longer crashes.
Change-Id: I2cb87a6071ecc2cbeb9df055f13039ad31fc6384
```
=> 1050: PEL: Check for Py_None from parser calls (#108)

extensions/openpower-pels/src.cpp, extensions/openpower-pels/user_data_json.cpp
```
Explicitly check if the UserData or SRC python plugin parsers return a
python None object and just return immediately.  In the UserData case
this results in a hex dump, and in the SRC case it just won't print the
SRC description.
Otherwise, peltool will crash when it tries to extract a string from the
result.
Tested:
peltool no longer crashes.
Change-Id: I2cb87a6071ecc2cbeb9df055f13039ad31fc6384
```
=> 1060: PEL: Check for Py_None from parser calls (#108)

extensions/openpower-pels/registry/message_registry.json
VPD parsing can be failed for both data and ECC errors for different records for a single file. So new generic error is introduced for exception occurred during VPD parsing.
=> Add VPD parsing error

extensions/openpower-pels/registry/message_registry.json
This commits adds JournalCapture in message_registry for VPD PELs to capture journals at the time of PEL.
=> Add journal trace for VPD PELs

extensions/openpower-pels/data_interface.cpp
Problem:
- It is observed intermittent core dumps from phosphor-log-manager during BMC graceful restart at OSRunning
- Journals show an abort() from dt_expand() in libpdbg immediately after openpower-update-bios-attr-table.service completes
Root cause:
- phosphor-logging subscribed to JobRemoved for openpower-update- bios-attr-table.service and kicked off PHAL init on that signal to avoid loading the default devtree
- In this window, obmc-recover-pnor.service which runs after the openpower-update-bios-attr-table.service may still accessing the devtree, so PHAL attempts to parse a devtree that isn’t ready, leading to libpdbg’s abort() in dt_expand() and a crash
Fix proposed:
- Switch Jobremoved watch from openpower-update-bios-attr-table. service to obmc-recover-pnor.service
=> PEL: FIX: Wait for obmc-recover-pnor before PHAL init

extensions/openpower-pels/data_interface.cpp
```
Problem:
- It is observed intermittent core dumps from phosphor-log-manager
during BMC graceful restart at OSRunning
- Journals show an abort() from dt_expand() in libpdbg immediately
after openpower-update-bios-attr-table.service completes
Root cause:
- phosphor-logging subscribed to JobRemoved for openpower-update-
bios-attr-table.service and kicked off PHAL init on that signal
to avoid loading the default devtree
- In this window, obmc-recover-pnor.service which runs after the
openpower-update-bios-attr-table.service may still accessing the
devtree, so PHAL attempts to parse a devtree that isn’t ready,
leading to libpdbg’s abort() in dt_expand() and a crash
Fix proposed:
- Switch Jobremoved watch from openpower-update-bios-attr-table.
service to obmc-recover-pnor.service
Tested: …
```
=> 1120: PEL: FIX: Wait for obmc-recover-pnor before PHAL init (#127)

extensions/openpower-pels/data_interface.cpp
```
Problem:
- It is observed intermittent core dumps from phosphor-log-manager
during BMC graceful restart at OSRunning
- Journals show an abort() from dt_expand() in libpdbg immediately
after openpower-update-bios-attr-table.service completes
Root cause:
- phosphor-logging subscribed to JobRemoved for openpower-update-
bios-attr-table.service and kicked off PHAL init on that signal
to avoid loading the default devtree
- In this window, obmc-recover-pnor.service which runs after the
openpower-update-bios-attr-table.service may still accessing the
devtree, so PHAL attempts to parse a devtree that isn’t ready,
leading to libpdbg’s abort() in dt_expand() and a crash
Fix proposed:
- Switch Jobremoved watch from openpower-update-bios-attr-table.
service to obmc-recover-pnor.service
Tested: …
```
=> 1060: PEL: FIX: Wait for obmc-recover-pnor before PHAL init (#127)
